ALTER TABLE "User"
ADD COLUMN "passwordHash" TEXT NOT NULL DEFAULT '';

ALTER TABLE "User"
ALTER COLUMN "passwordHash" DROP DEFAULT;

ALTER TABLE "Character"
ADD COLUMN "experience" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "health" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN "maxHealth" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN "mana" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN "maxMana" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN "x" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN "y" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN "z" INTEGER NOT NULL DEFAULT 0;

CREATE INDEX "Character_userId_idx" ON "Character"("userId");
